version: "2.1"
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /home/brett/docker/sonarr:/config
      - /mnt/data/Plex:/tv #optional
      - /mnt/data/Plex/Torrents:/downloads
    network_mode: container:openvpn-client
    restart: unless-stopped
