version: '3.3'
services:
    linuxserver:
        image: lscr.io/linuxserver/plex:latest
        container_name: plex
        network_mode: host
        environment:
            - PUID=1000
            - PGID=1000
            - VERSION=docker
            - PLEX_CLAIM=claim-1xe2kkSWm3mvBmUMtfBG
        volumes:
            - '/home/brett/docker/plex:/config'
            - '/mnt/data/Plex:/media'
        devices:
            - '/dev/dri:/dev/dri'
        restart: unless-stopped
