version: '3.3'

services:
  authelia:
    image: authelia/authelia:4.37.5
    container_name: authelia
    volumes:
      - /home/brett/docker/authelia:/config #change this to a shared folder on your system. DO NOT use a "volume"
    ports:
      - 9091:9091
    environment:
      - TZ=America/New_York
    restart: unless-stopped
