version: '3.3'
services:
    iqbit:
        container_name: iQbit
        ports:
            - '8081:8081'
        environment:
            - 'QBIT_HOST=http://192.168.1.173:8080'
        image: iqbit:2.0
        restart: unless-stopped
