version: "3"
services:
  front:
    image: tombursch/kitchenowl-web:latest
    restart: unless-stopped
    ports:
      - "9926:80"
    depends_on:
      - back
  back:
    image: tombursch/kitchenowl:latest
    restart: unless-stopped
    environment:
      - JWT_SECRET_KEY=eyJhbGciOiJIUzI1NiJ9.eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTY5NDI4NDgwNCwiaWF0IjoxNjk0Mjg0ODA0fQ.7WaLPlB98w2wfWCv7Omq0GZPwlns0GVifJ-eCJDNeFI
    volumes:
      - kitchenowl_data:/data

volumes:
  kitchenowl_data:
