version: "3"
services:
  guacamole:
    image: abesnier/guacamole
    container_name: guacamole
    volumes:
      - /home/brett/docker/guac/config:/config
    ports:
      - 8084:8080
    restart: unless-stopped
