version: "3.3"
services:
    uptime-kuma:
        image: louislam/uptime-kuma:1.22.1
        container_name: uptime-kuma
        restart: unless-stopped
        ports:
            - 3001:3001
        volumes:
            - /home/brett/docker/kuma/data:/app/data
